// app/lib/petTypes.ts
// 16가지 반려동물-보호자 케미 유형 데이터 (Big Five 기반 4축 High/Low 조합)
// 4축: E(활력) / S(사교성) / A(친화성) / C(침착성)
// 각 축이 High(H) 또는 Low(L) → 2^4 = 16 유형

export type Locale = "ko" | "en" | "de" | "es" | "zh" | "ja" | "ar";

export type AxisLevel = "H" | "L";

export interface TypeCode {
  E: AxisLevel; // Energy - 활력
  S: AxisLevel; // Sociability - 사교성
  A: AxisLevel; // Agreeableness - 친화성
  C: AxisLevel; // Calmness - 침착성
}

export interface TypeContent {
  slug: string;              // URL slug: e-h-s-h-a-h-c-h
  code: string;              // 표시용 코드: EHSH-AHCH 또는 HHHH
  emoji: string;             // 대표 이모지
  nickname: Record<Locale, string>;      // "탐험가 콤비"
  tagline: Record<Locale, string>;       // 한 줄 요약
  description: Record<Locale, string>;   // 유형 상세 설명 (500-800자)
  strengths: Record<Locale, string[]>;   // 강점 3-5개
  cautions: Record<Locale, string[]>;    // 주의점 3-5개
  activities: Record<Locale, string[]>;  // 추천 활동 4-6개
  matchBest: string[];                   // 잘 맞는 유형 코드 배열
  matchChallenge: string[];              // 궁합 어려운 유형 코드 배열
}

// 4축 High/Low 조합 16가지 정의
export const TYPE_AXES: TypeCode[] = [
  { E: "H", S: "H", A: "H", C: "H" }, // 1 - 궁극의 낙천가
  { E: "H", S: "H", A: "H", C: "L" }, // 2 - 열정 폭발형
  { E: "H", S: "H", A: "L", C: "H" }, // 3 - 리더형
  { E: "H", S: "H", A: "L", C: "L" }, // 4 - 파티 스타
  { E: "H", S: "L", A: "H", C: "H" }, // 5 - 조용한 모험가
  { E: "H", S: "L", A: "H", C: "L" }, // 6 - 열정 탐험가
  { E: "H", S: "L", A: "L", C: "H" }, // 7 - 독립 사냥꾼
  { E: "H", S: "L", A: "L", C: "L" }, // 8 - 자유로운 영혼
  { E: "L", S: "H", A: "H", C: "H" }, // 9 - 평화의 수호자
  { E: "L", S: "H", A: "H", C: "L" }, // 10 - 감성 소통가
  { E: "L", S: "H", A: "L", C: "H" }, // 11 - 사교 관찰자
  { E: "L", S: "H", A: "L", C: "L" }, // 12 - 예민한 관계자
  { E: "L", S: "L", A: "H", C: "H" }, // 13 - 명상형 힐러
  { E: "L", S: "L", A: "H", C: "L" }, // 14 - 조용한 감성가
  { E: "L", S: "L", A: "L", C: "H" }, // 15 - 고독한 현자
  { E: "L", S: "L", A: "L", C: "L" }, // 16 - 신비의 은둔자
];

// slug 생성: E-h-s-h-a-h-c-h 형식
export function makeSlug(code: TypeCode): string {
  return `e-${code.E.toLowerCase()}-s-${code.S.toLowerCase()}-a-${code.A.toLowerCase()}-c-${code.C.toLowerCase()}`;
}

// 표시용 코드: HHHH, HHHL, ...
export function makeDisplayCode(code: TypeCode): string {
  return `${code.E}${code.S}${code.A}${code.C}`;
}

// 16개 유형 완전 데이터
export const TYPES: TypeContent[] = [
  // ============ 1. HHHH - 궁극의 낙천가 ============
  {
    slug: "e-h-s-h-a-h-c-h",
    code: "HHHH",
    emoji: "🌟",
    nickname: {
      ko: "궁극의 낙천가 콤비",
      en: "Ultimate Optimist Duo",
      de: "Der ultimative Optimist",
      es: "El Dúo Optimista Definitivo",
      zh: "终极乐天派组合",
      ja: "究極の楽天家コンビ",
      ar: "الثنائي المتفائل المطلق",
    },
    tagline: {
      ko: "에너지·사교·친화·침착 모두 갖춘 완벽 밸런스 콤비",
      en: "The perfectly balanced pair with high energy, sociability, warmth, and calm.",
      de: "Das perfekt ausgewogene Paar mit hoher Energie, Geselligkeit, Wärme und Ruhe.",
      es: "La pareja perfectamente equilibrada con alta energía, sociabilidad, calidez y calma.",
      zh: "精力充沛、社交活跃、亲和力强、沉着冷静的完美平衡组合",
      ja: "エネルギー・社交性・親和性・冷静さすべてを兼ね備えた完璧なバランスコンビ",
      ar: "الثنائي المتوازن تماماً مع طاقة عالية واجتماعية ودفء وهدوء.",
    },
    description: {
      ko: "이 콤비는 활력·사교성·친화성·침착성이 모두 높은 극도로 균형 잡힌 케미입니다. 새로운 사람이나 환경에도 능숙하게 적응하고, 반려동물 역시 낯선 자극에 크게 흔들리지 않습니다. 함께 산책·여행·모임 어디를 가도 자연스럽게 어울리며, 서로의 감정 신호를 읽는 능력이 뛰어나 갈등이 거의 없습니다. Big Five 연구에서 이 조합은 '가장 안정적인 애착 유형'으로 분류되며, 특히 사회화 훈련이 잘 된 반려견이나 오랫동안 다양한 환경을 경험한 반려묘에서 자주 나타납니다.",
      en: "This duo shows extreme balance with high energy, sociability, agreeableness, and calmness. Both adapt gracefully to new people and environments, and your pet handles unfamiliar stimuli without stress. From walks to travel to gatherings, you fit in naturally. Your ability to read each other's emotional signals is exceptional, resulting in minimal conflict. Big Five research classifies this combination as the 'most secure attachment type,' commonly found in well-socialized dogs or cats with diverse life experiences.",
      de: "Dieses Duo zeigt extreme Balance mit hoher Energie, Geselligkeit, Verträglichkeit und Ruhe. Beide passen sich anmutig an neue Menschen und Umgebungen an, und Ihr Haustier bewältigt unbekannte Reize ohne Stress. Von Spaziergängen bis Reisen fügen Sie sich natürlich ein.",
      es: "Este dúo muestra un equilibrio extremo con alta energía, sociabilidad, amabilidad y calma. Ambos se adaptan con gracia a nuevas personas y entornos, y tu mascota maneja estímulos desconocidos sin estrés.",
      zh: "这个组合展现出极致的平衡：高活力、高社交、高亲和、高冷静。你们优雅地适应新的人和环境，宠物也能从容应对陌生刺激。",
      ja: "このコンビは活力・社交性・親和性・冷静さがすべて高く、極めてバランスの取れたケミストリーです。新しい人や環境にも巧みに適応し、ペットも見知らぬ刺激に大きく動揺しません。",
      ar: "يُظهر هذا الثنائي توازناً استثنائياً مع طاقة عالية واجتماعية ولطف وهدوء. كلاكما يتكيف بأناقة مع الأشخاص والبيئات الجديدة.",
    },
    strengths: {
      ko: ["새로운 상황에도 서로를 안정시키는 감정 조절 능력", "산책·여행·모임 등 다양한 활동을 함께 즐김", "긍정적 강화 훈련이 매우 잘 통함", "낯선 반려동물·사람과도 원만한 관계 형성"],
      en: ["Emotional regulation that stabilizes each other in new situations", "Enjoys diverse activities together — walks, travel, gatherings", "Highly responsive to positive-reinforcement training", "Forms smooth relationships with unfamiliar pets and people"],
      de: ["Emotionale Regulation, die sich in neuen Situationen gegenseitig stabilisiert", "Genießt vielfältige Aktivitäten zusammen — Spaziergänge, Reisen, Zusammenkünfte", "Reagiert sehr gut auf positives Verstärkungstraining"],
      es: ["Regulación emocional que se estabiliza mutuamente en situaciones nuevas", "Disfruta de diversas actividades juntos — paseos, viajes, reuniones", "Muy receptivo al entrenamiento de refuerzo positivo"],
      zh: ["在新情境中相互稳定的情绪调节能力", "共同享受多样活动 — 散步、旅行、聚会", "对正向强化训练反应极佳"],
      ja: ["新しい状況でも互いを安定させる感情調整能力", "散歩・旅行・集まりなど多様な活動を一緒に楽しむ", "ポジティブ強化トレーニングが非常によく効く"],
      ar: ["تنظيم عاطفي يستقر متبادلاً في المواقف الجديدة", "الاستمتاع بأنشطة متنوعة معاً — المشي والسفر والتجمعات", "استجابة عالية للتدريب بالتعزيز الإيجابي"],
    },
    cautions: {
      ko: ["활동량이 과잉되어 반려동물이 지칠 수 있음 → 충분한 휴식 확보", "너무 자주 새로운 자극을 주면 무뎌질 수 있음", "다른 반려동물과 접촉 시 과잉 사회화 주의"],
      en: ["Overactivity can exhaust your pet — ensure adequate rest", "Constant new stimuli may dull excitement over time", "Watch for over-socialization when meeting other pets"],
      de: ["Überaktivität kann Ihr Haustier erschöpfen — sorgen Sie für ausreichend Ruhe", "Ständig neue Reize können die Aufregung mit der Zeit abstumpfen"],
      es: ["La sobreactividad puede agotar a tu mascota — asegura descanso adecuado", "Estímulos nuevos constantes pueden mermar la emoción con el tiempo"],
      zh: ["过度活跃可能使宠物疲惫 — 确保充足休息", "频繁的新刺激可能随时间变得麻木"],
      ja: ["活動量が過剰でペットが疲れる可能性 → 十分な休息の確保", "頻繁に新しい刺激を与えると鈍くなる可能性"],
      ar: ["قد يُنهك النشاط المفرط حيوانك الأليف — ضمان الراحة الكافية", "المحفزات الجديدة المستمرة قد تُخفف الحماس بمرور الوقت"],
    },
    activities: {
      ko: ["애견 카페·펫 프렌들리 여행지 함께 방문", "새로운 산책 코스 매주 개척하기", "펫 스포츠(어질리티·프리스비) 도전", "다양한 반려동물 친구와 정기 모임", "집에서 함께 하는 트릭 트레이닝 세션"],
      en: ["Visit pet cafés and pet-friendly travel destinations together", "Explore a new walking route every week", "Try pet sports like agility or frisbee", "Host regular meetups with other pet friends", "Do trick training sessions at home together"],
      de: ["Besuchen Sie zusammen Haustier-Cafés und haustierfreundliche Reiseziele", "Erkunden Sie jede Woche eine neue Spazierroute", "Probieren Sie Haustier-Sportarten wie Agility oder Frisbee"],
      es: ["Visita cafés pet-friendly y destinos de viaje pet-friendly juntos", "Explora una nueva ruta de paseo cada semana", "Prueba deportes de mascotas como agility o frisbee"],
      zh: ["共同拜访宠物咖啡厅和宠物友好旅行地", "每周探索新的散步路线", "尝试敏捷或飞盘等宠物运动"],
      ja: ["ペットカフェやペットフレンドリーな旅行先へ一緒に訪問", "新しい散歩コースを毎週開拓する", "アジリティやフリスビーなどのペットスポーツに挑戦"],
      ar: ["زيارة مقاهي الحيوانات الأليفة ووجهات السفر الصديقة للحيوانات معاً", "استكشاف مسار مشي جديد كل أسبوع", "تجربة رياضات الحيوانات الأليفة مثل الرشاقة أو الفريسبي"],
    },
    matchBest: ["HHHL", "HHLH", "LHHH"],
    matchChallenge: ["LLLL", "LLLH"],
  },

  // ============ 2. HHHL - 열정 폭발형 ============
  {
    slug: "e-h-s-h-a-h-c-l",
    code: "HHHL",
    emoji: "🎉",
    nickname: {
      ko: "열정 폭발형 콤비",
      en: "Passionate Explosion Duo",
      de: "Das leidenschaftliche Explosionsduo",
      es: "El Dúo Explosivo Apasionado",
      zh: "热情爆发型组合",
      ja: "情熱爆発型コンビ",
      ar: "ثنائي الشغف المتفجر",
    },
    tagline: {
      ko: "활력·사교·친화 모두 최고, 침착함은 살짝 부족한 열정 만점 콤비",
      en: "Peak energy, sociability, and warmth — with a dash of joyful impulsiveness.",
      de: "Höchste Energie, Geselligkeit und Wärme — mit einer Prise fröhlicher Impulsivität.",
      es: "Máxima energía, sociabilidad y calidez — con un toque de impulsividad alegre.",
      zh: "活力、社交、亲和力都满分，略带一丝冲动的热情组合",
      ja: "活力・社交性・親和性すべて最高、冷静さは少し不足の情熱満点コンビ",
      ar: "أقصى طاقة واجتماعية ودفء - مع لمسة من الاندفاع البهيج.",
    },
    description: {
      ko: "이 콤비는 감정 표현이 풍부하고 사랑이 넘칩니다. 반려동물이 흥분하기 쉬운 만큼 보호자도 함께 들뜨는 경향이 있어 집안 분위기가 늘 활기찹니다. 다만 침착성이 낮아 예측 못한 자극(초인종·큰 소음·낯선 방문객)에 과잉 반응할 수 있습니다. Big Five 연구에 따르면 이 유형의 반려동물은 '외향적 흥분자(Extroverted Arouser)'로 분류되며, 보호자의 정서적 안정 신호를 매우 빠르게 학습하므로 침착 훈련을 조금만 해도 큰 효과를 봅니다.",
      en: "This duo overflows with expressive love. Your pet gets excited easily, and you tend to match that energy, making your home lively at all times. However, low calmness means both can overreact to unexpected stimuli — doorbells, loud noises, unfamiliar visitors. Big Five research classifies this type as 'Extroverted Arouser,' which learns emotional regulation cues from owners very quickly, so even minimal calm-training yields large gains.",
      de: "Dieses Duo strömt vor ausdrucksstarker Liebe über. Ihr Haustier wird leicht aufgeregt, und Sie neigen dazu, diese Energie zu spiegeln.",
      es: "Este dúo rebosa amor expresivo. Tu mascota se emociona fácilmente y tú tiendes a igualar esa energía.",
      zh: "这个组合充满表达性的爱。宠物容易兴奋，你也倾向于配合这种能量，让家中始终充满活力。",
      ja: "このコンビは感情表現が豊かで愛情に溢れています。ペットが興奮しやすく、飼い主も一緒に浮き立つ傾向があります。",
      ar: "يفيض هذا الثنائي بالحب المُعبِّر. يُثار حيوانك الأليف بسهولة، وتميل إلى مطابقة تلك الطاقة.",
    },
    strengths: {
      ko: ["애정 표현이 자연스럽고 서로 즉각 반응", "가족·친구 모임에서 분위기 메이커", "감정 신호가 명확해 소통 오해가 적음", "새로운 사람·환경을 즐기는 편"],
      en: ["Affection flows naturally and reactions are immediate", "Life of the party in family and friend gatherings", "Clear emotional signals reduce communication errors", "Enjoys new people and environments"],
      de: ["Zuneigung fließt natürlich und Reaktionen sind unmittelbar", "Stimmungsmacher bei Familien- und Freundetreffen"],
      es: ["El afecto fluye naturalmente y las reacciones son inmediatas", "Alma de la fiesta en reuniones familiares y de amigos"],
      zh: ["感情表达自然，反应即时", "家庭和朋友聚会的气氛制造者"],
      ja: ["愛情表現が自然で互いに即座に反応", "家族・友人の集まりで雰囲気メーカー"],
      ar: ["يتدفق الود بشكل طبيعي والاستجابات فورية", "روح الحفلة في تجمعات العائلة والأصدقاء"],
    },
    cautions: {
      ko: ["큰 소음·낯선 방문객에 과잉 반응 주의", "너무 흥분하면 반려동물이 지침 → 진정 시간 필수", "혼자 있는 시간에 분리불안 발생 가능", "훈련 시 명령이 일관되지 않으면 혼란"],
      en: ["Watch for overreactions to loud noises or unfamiliar visitors", "Excessive excitement leads to exhaustion — set calm-down time", "Separation anxiety may develop during alone time", "Inconsistent commands during training cause confusion"],
      de: ["Achten Sie auf Überreaktionen bei lauten Geräuschen"],
      es: ["Cuidado con las sobrerreacciones a ruidos fuertes"],
      zh: ["注意对巨响或陌生访客的过度反应"],
      ja: ["大きな音や見知らぬ訪問客に過剰反応する可能性に注意"],
      ar: ["احترس من ردود الفعل المبالغ فيها تجاه الأصوات العالية"],
    },
    activities: {
      ko: ["침착 훈련(마사지·손 노즈워크)", "정기적 사회화 산책 (같은 시간대·경로)", "코스 놀이 (터그·페치)로 에너지 배출", "저녁 명상 시간을 함께 갖기", "새로운 트릭 매주 한 개씩 배우기"],
      en: ["Calm training — gentle massage and nose work", "Regular socialization walks (same time and route)", "Course play (tug, fetch) for energy release", "Evening calm-down sessions together", "Learn one new trick weekly"],
      de: ["Ruhe-Training — sanfte Massage und Nasenarbeit"],
      es: ["Entrenamiento de calma — masaje suave y trabajo olfativo"],
      zh: ["冷静训练 — 轻柔按摩和嗅闻游戏"],
      ja: ["落ち着きトレーニング(マッサージ・ノーズワーク)"],
      ar: ["تدريب الهدوء - التدليك اللطيف والعمل بالأنف"],
    },
    matchBest: ["HHHH", "HHLL", "LHHL"],
    matchChallenge: ["LLLH", "LLHH"],
  },

  // ============ 3. HHLH - 리더형 ============
  {
    slug: "e-h-s-h-a-l-c-h",
    code: "HHLH",
    emoji: "👑",
    nickname: {
      ko: "리더형 콤비",
      en: "Leader Duo",
      de: "Das Anführer-Duo",
      es: "El Dúo Líder",
      zh: "领袖型组合",
      ja: "リーダー型コンビ",
      ar: "الثنائي القائد",
    },
    tagline: {
      ko: "활력·사교·침착 모두 높지만 친화성은 낮은 카리스마 콤비",
      en: "High energy, sociability, and calmness — but selective in warmth.",
      de: "Hohe Energie, Geselligkeit und Ruhe — aber selektiv in der Wärme.",
      es: "Alta energía, sociabilidad y calma — pero selectivo en calidez.",
      zh: "高活力、高社交、高冷静，但亲和力低的魅力组合",
      ja: "活力・社交性・冷静さは高いが親和性は低いカリスマコンビ",
      ar: "طاقة عالية واجتماعية وهدوء - ولكن انتقائي في الدفء.",
    },
    description: {
      ko: "이 유형은 자신감이 강하고 자기 영역을 명확히 지키는 반려동물과 그 성향을 존중하는 보호자의 조합입니다. 사교적이지만 아무나 가까이 두지 않는 '친구 선별력'이 뛰어납니다. 반려동물은 신뢰하는 상대에게는 무한한 애정을 보이지만 낯선 존재에게는 경계 신호를 확실히 보냅니다. 이 조합은 리더십이 필요한 다견·다묘 가정에서 특히 안정적이며, Big Five 연구에서 '경계 명확형 리더(Assertive Guardian)'로 분류됩니다.",
      en: "This type combines a confident, territorial pet with an owner who respects that nature. Sociable yet highly selective — they choose friends carefully. Your pet shows infinite affection to trusted individuals but sends clear warning signals to strangers. This combination is especially stable in multi-pet households requiring leadership, classified as 'Assertive Guardian' in Big Five research.",
      de: "Dieser Typ kombiniert ein selbstbewusstes, territoriales Haustier mit einem Besitzer, der diese Natur respektiert.",
      es: "Este tipo combina una mascota confiada y territorial con un dueño que respeta esa naturaleza.",
      zh: "这个类型结合了自信、有领地意识的宠物和尊重这一天性的主人。",
      ja: "このタイプは自信が強く自分の領域を明確に守るペットとその性向を尊重する飼い主の組み合わせです。",
      ar: "يجمع هذا النوع بين حيوان أليف واثق وإقليمي ومالك يحترم هذه الطبيعة.",
    },
    strengths: {
      ko: ["명확한 규칙과 경계가 있어 훈련 효과가 큼", "다른 반려동물 사이에서 자연스러운 리더 역할", "신뢰 관계 형성 후 극도로 충성적", "위험 상황에서 보호자를 지키려는 본능"],
      en: ["Clear rules and boundaries make training very effective", "Natural leadership role among other pets", "Extreme loyalty once trust is established", "Instinct to protect owner in dangerous situations"],
      de: ["Klare Regeln und Grenzen machen das Training sehr effektiv"],
      es: ["Reglas y límites claros hacen el entrenamiento muy efectivo"],
      zh: ["明确的规则和界限使训练非常有效"],
      ja: ["明確なルールと境界があり訓練効果が大きい"],
      ar: ["القواعد والحدود الواضحة تجعل التدريب فعالاً للغاية"],
    },
    cautions: {
      ko: ["낯선 반려동물·사람에 공격성 표출 가능", "사회화가 부족하면 소유욕 문제 발생", "권위주의적 훈련은 역효과 → 상호 존중 필수", "다견·다묘 가정에서 서열 갈등 조율 필요"],
      en: ["May show aggression toward unfamiliar pets or people", "Poor socialization leads to possessiveness", "Authoritarian training backfires — mutual respect is key", "Hierarchy conflicts in multi-pet homes need mediation"],
      de: ["Kann Aggression gegenüber unbekannten Haustieren zeigen"],
      es: ["Puede mostrar agresión hacia mascotas o personas desconocidas"],
      zh: ["可能对陌生宠物或人表现出攻击性"],
      ja: ["見知らぬペットや人に攻撃性を示す可能性"],
      ar: ["قد يظهر عدوانية تجاه الحيوانات أو الأشخاص غير المألوفين"],
    },
    activities: {
      ko: ["초기부터 다양한 사회화 경험 제공", "리더십 훈련(집중·기다려·따라와)", "구조화된 놀이 (규칙 있는 게임)", "특정 신뢰 대상 소수와 정기 교류", "영역 놀이 (자기 공간 만들기)"],
      en: ["Provide diverse socialization from early age", "Leadership training — focus, wait, follow commands", "Structured play with rules", "Regular interaction with a small circle of trusted friends", "Territory play — creating their own space"],
      de: ["Bieten Sie von klein auf vielfältige Sozialisation"],
      es: ["Proporciona socialización diversa desde temprana edad"],
      zh: ["从小提供多样化的社交经验"],
      ja: ["幼少期から多様な社会化経験を提供"],
      ar: ["توفير التنشئة الاجتماعية المتنوعة من سن مبكرة"],
    },
    matchBest: ["HHHH", "HLLH", "LHLH"],
    matchChallenge: ["LLHL", "LHHL"],
  },

  // ============ 4. HHLL - 파티 스타 ============
  {
    slug: "e-h-s-h-a-l-c-l",
    code: "HHLL",
    emoji: "🎊",
    nickname: {
      ko: "파티 스타 콤비",
      en: "Party Star Duo",
      de: "Das Party-Star-Duo",
      es: "El Dúo Estrella de Fiesta",
      zh: "派对之星组合",
      ja: "パーティースター コンビ",
      ar: "ثنائي نجم الحفلة",
    },
    tagline: {
      ko: "활력·사교 최고, 친화·침착은 낮은 자유분방 콤비",
      en: "Maximum energy and sociability with untamed spontaneity.",
      de: "Maximale Energie und Geselligkeit mit ungezähmter Spontaneität.",
      es: "Máxima energía y sociabilidad con espontaneidad indomable.",
      zh: "活力和社交性最高、亲和力和冷静度较低的自由奔放组合",
      ja: "活力・社交性最高、親和性・冷静さは低い自由奔放コンビ",
      ar: "أقصى طاقة واجتماعية مع عفوية جامحة.",
    },
    description: {
      ko: "이 콤비는 함께 있는 것만으로도 어디든 축제가 됩니다. 활력과 사교성이 극도로 높아 새로운 자극을 늘 찾고, 반려동물은 낯선 환경에서도 겁 없이 뛰어듭니다. 다만 친화성과 침착성이 낮아 서로 감정 컨트롤이 서투르고 즉흥적입니다. 이 유형은 반려동물 이벤트, 산책 모임, 카페 방문에서 최고의 매력을 발휘하지만, 갑작스러운 자극에 폭주할 수 있어 리드줄·하네스는 필수입니다.",
      en: "This duo turns any place into a party by simply being there. Extreme energy and sociability drive constant thrill-seeking, and your pet fearlessly leaps into new environments. However, low agreeableness and calmness mean impulsive emotional control. Perfect for pet events, walking groups, and cafés — but leashes and harnesses are non-negotiable due to sudden bursts.",
      de: "Dieses Duo verwandelt jeden Ort in eine Party.",
      es: "Este dúo convierte cualquier lugar en una fiesta.",
      zh: "这个组合只要在场就能把任何地方变成派对。",
      ja: "このコンビは一緒にいるだけでどこでもお祭りになります。",
      ar: "يحول هذا الثنائي أي مكان إلى حفلة بمجرد التواجد فيه.",
    },
    strengths: {
      ko: ["어디를 가도 자연스럽게 관심을 끄는 매력", "새로운 자극을 두려워하지 않음", "즉흥 여행·활동에 최적", "사회화 훈련 초기 반응이 빠름"],
      en: ["Naturally attracts attention wherever you go", "Fearless with new stimuli", "Perfect for spontaneous trips and activities", "Fast initial response to socialization training"],
      de: ["Zieht natürlich Aufmerksamkeit auf sich, wohin Sie auch gehen"],
      es: ["Atrae naturalmente la atención dondequiera que vaya"],
      zh: ["无论去哪都自然吸引注意"],
      ja: ["どこへ行っても自然に注目を集める魅力"],
      ar: ["يجذب الانتباه بشكل طبيعي أينما ذهبت"],
    },
    cautions: {
      ko: ["갑작스러운 폭주 위험 → 안전 장비 필수", "충동성이 높아 사고 위험 증가", "다른 반려동물과 충돌 시 진정 어려움", "일관된 훈련이 어려움 → 짧고 자주"],
      en: ["Sudden bursts risk safety — gear is essential", "High impulsivity increases accident risk", "Hard to calm after conflict with other pets", "Consistent training is difficult — keep sessions short and frequent"],
      de: ["Plötzliche Ausbrüche gefährden die Sicherheit"],
      es: ["Los estallidos súbitos ponen en riesgo la seguridad"],
      zh: ["突然的爆发有安全风险"],
      ja: ["突然の暴走のリスク → 安全装備必須"],
      ar: ["الاندفاعات المفاجئة تُهدد السلامة"],
    },
    activities: {
      ko: ["펫 이벤트·강아지 운동회 참가", "짧고 강도 높은 놀이 (10분 x 3회)", "노즈워크 매트로 두뇌 활동", "반려동물 친구와 자유 놀이터 방문", "매주 새로운 장소 탐험"],
      en: ["Attend pet events and dog sports days", "Short, high-intensity play (10 min x 3)", "Nose work mats for cognitive exercise", "Free-play sessions at dog parks with pet friends", "Explore a new location every week"],
      de: ["Nehmen Sie an Haustier-Events teil"],
      es: ["Asiste a eventos de mascotas"],
      zh: ["参加宠物活动"],
      ja: ["ペットイベント・犬の運動会に参加"],
      ar: ["حضور فعاليات الحيوانات الأليفة"],
    },
    matchBest: ["HHHL", "HHHH", "LHHL"],
    matchChallenge: ["LLLH", "LLHH"],
  },

  // ============ 5. HLHH - 조용한 모험가 ============
  {
    slug: "e-h-s-l-a-h-c-h",
    code: "HLHH",
    emoji: "🏔️",
    nickname: {
      ko: "조용한 모험가 콤비",
      en: "Quiet Adventurer Duo",
      de: "Das stille Abenteurer-Duo",
      es: "El Dúo Aventurero Tranquilo",
      zh: "静默冒险家组合",
      ja: "静かな冒険家コンビ",
      ar: "ثنائي المغامر الهادئ",
    },
    tagline: {
      ko: "활동적이지만 낯선 사람은 부담스러운 소수정예 콤비",
      en: "Active and warm, but prefers a small circle over big crowds.",
      de: "Aktiv und warmherzig, bevorzugt aber einen kleinen Kreis vor großen Menschenmengen.",
      es: "Activo y cálido, pero prefiere un círculo pequeño a las multitudes.",
      zh: "活跃且亲和，但相对陌生人来说更喜欢小圈子",
      ja: "活動的だが見知らぬ人は苦手な少数精鋭コンビ",
      ar: "نشط ودافئ ولكنه يُفضّل الدائرة الصغيرة على الحشود الكبيرة.",
    },
    description: {
      ko: "활동량은 많지만 시끄러운 곳보다 조용하고 낯익은 공간에서 편안함을 느끼는 콤비입니다. 반려동물은 익숙한 산책 코스에서 최고의 컨디션을 보이며, 낯선 사람에게는 무관심하거나 살짝 거리를 둡니다. 보호자도 대규모 모임보다 소수의 신뢰하는 친구들과 자연 속 시간을 선호합니다. 이 유형은 하이킹·캠핑·자연 산책에서 진가를 발휘합니다.",
      en: "High activity but preference for quiet, familiar spaces over crowded venues. Your pet performs best on familiar walking routes and remains detached or slightly distant with strangers. You also prefer small circles of trusted friends and nature time over large gatherings. This type thrives in hiking, camping, and nature walks.",
      de: "Hohe Aktivität, aber Bevorzugung von ruhigen, vertrauten Räumen.",
      es: "Alta actividad pero preferencia por espacios tranquilos y familiares.",
      zh: "活动量大但偏好安静、熟悉的空间胜过拥挤场所。",
      ja: "活動量は多いが騒がしい所より静かで馴染みの空間で安らぎを感じるコンビ。",
      ar: "نشاط عالٍ لكن يُفضّل الأماكن الهادئة والمألوفة على الأماكن المزدحمة.",
    },
    strengths: {
      ko: ["장거리 산책·하이킹에 최적", "익숙한 환경에서 안정감 최고", "소수의 신뢰 관계 매우 깊음", "훈련 집중도가 높음"],
      en: ["Perfect for long walks and hiking", "Maximum stability in familiar environments", "Deep bonds with a small trusted circle", "High training focus"],
      de: ["Perfekt für lange Spaziergänge und Wandern"],
      es: ["Perfecto para caminatas largas y senderismo"],
      zh: ["非常适合长途散步和徒步"],
      ja: ["長距離散歩・ハイキングに最適"],
      ar: ["مثالي للمشي الطويل والمشي لمسافات طويلة"],
    },
    cautions: {
      ko: ["갑작스러운 낯선 방문객에 스트레스", "펫 카페·이벤트는 짧게", "새 환경 적응에 시간 필요", "장시간 소음 노출 주의"],
      en: ["Sudden unfamiliar visitors cause stress", "Keep pet café and event visits short", "Needs time to adapt to new environments", "Watch for prolonged noise exposure"],
      de: ["Plötzliche unbekannte Besucher verursachen Stress"],
      es: ["Visitantes desconocidos súbitos causan estrés"],
      zh: ["突然的陌生访客会造成压力"],
      ja: ["突然の見知らぬ訪問客にストレス"],
      ar: ["الزوار غير المألوفين المفاجئون يُسببون التوتر"],
    },
    activities: {
      ko: ["숲길 하이킹·트레킹", "정해진 산책 루트 매일 걷기", "1:1 훈련 세션", "차분한 실내 지능 놀이", "캠핑·차박 여행"],
      en: ["Forest hiking and trekking", "Daily walk on set routes", "1:1 training sessions", "Calm indoor puzzle games", "Camping and van trips"],
      de: ["Waldwanderungen und Trekking"],
      es: ["Senderismo forestal y trekking"],
      zh: ["森林徒步和跋涉"],
      ja: ["森の道のハイキング・トレッキング"],
      ar: ["المشي في الغابات والرحلات الطويلة"],
    },
    matchBest: ["HLHL", "LLHH", "HHHH"],
    matchChallenge: ["HHLL", "LLLL"],
  },

  // ============ 6. HLHL - 열정 탐험가 ============
  {
    slug: "e-h-s-l-a-h-c-l",
    code: "HLHL",
    emoji: "🔥",
    nickname: {
      ko: "열정 탐험가 콤비",
      en: "Passionate Explorer Duo",
      de: "Das leidenschaftliche Entdecker-Duo",
      es: "El Dúo Explorador Apasionado",
      zh: "热情探险家组合",
      ja: "情熱探検家コンビ",
      ar: "ثنائي المستكشف الشغوف",
    },
    tagline: {
      ko: "활동적이고 다정하지만 감정 기복이 있는 예민한 탐험가",
      en: "Active and warm-hearted, but emotionally sensitive explorer.",
      de: "Aktiver und warmherziger, aber emotional sensibler Entdecker.",
      es: "Explorador activo y cálido, pero emocionalmente sensible.",
      zh: "活跃、亲和但情绪起伏较大的敏感探险家",
      ja: "活動的で優しいが感情の起伏がある敏感な探検家",
      ar: "مستكشف نشط وحنون ولكنه حساس عاطفياً.",
    },
    description: {
      ko: "이 콤비는 반려동물과 보호자 모두 감정이 풍부하고 표현이 강한 편입니다. 좋아하는 사람에게는 극도의 애정을 표현하지만, 스트레스 상황에서는 예민하게 반응합니다. 자연 속에서 자유롭게 뛰노는 시간을 매우 좋아하며, 규모가 큰 모임보다는 익숙한 친구 몇 명과 함께 있는 것을 선호합니다.",
      en: "Both pet and owner are emotionally rich and expressive. Extreme affection for loved ones, but sensitive reactions under stress. Loves free-range play in nature, prefers a small group of familiar friends over large gatherings.",
      de: "Sowohl Haustier als auch Besitzer sind emotional reich und ausdrucksstark.",
      es: "Tanto la mascota como el dueño son emocionalmente ricos y expresivos.",
      zh: "宠物和主人都情感丰富、表达强烈。",
      ja: "このコンビはペットも飼い主も感情豊かで表現が強い方です。",
      ar: "كل من الحيوان الأليف والمالك غنيان عاطفياً ومعبران.",
    },
    strengths: {
      ko: ["감정 교류 풍부", "자연·야외 활동 최적", "1:1 관계에서 최고 성과", "따뜻한 애정 표현"],
      en: ["Rich emotional exchange", "Perfect for nature and outdoor activities", "Excels in 1:1 relationships", "Warm affection"],
      de: ["Reicher emotionaler Austausch"],
      es: ["Rico intercambio emocional"],
      zh: ["丰富的情感交流"],
      ja: ["感情交流が豊か"],
      ar: ["تبادل عاطفي غني"],
    },
    cautions: {
      ko: ["스트레스에 예민 → 안전한 공간 필수", "감정 폭발 시 진정 시간 확보", "너무 자주 이동하면 지침", "새 반려동물 도입 시 신중"],
      en: ["Stress-sensitive — safe space is essential", "Allow calm-down time after emotional outbursts", "Frequent travel causes exhaustion", "Careful introduction of new pets"],
      de: ["Stressempfindlich"],
      es: ["Sensible al estrés"],
      zh: ["对压力敏感"],
      ja: ["ストレスに敏感"],
      ar: ["حساس للضغط"],
    },
    activities: {
      ko: ["숲·바다 등 자연 산책", "감정 안정 마사지", "구조화된 노즈워크", "정기적 1:1 놀이 시간", "차분한 음악과 함께 휴식"],
      en: ["Nature walks in forests and beaches", "Emotional-calm massage", "Structured nose work", "Regular 1:1 play time", "Rest with calming music"],
      de: ["Naturspaziergänge"],
      es: ["Paseos por la naturaleza"],
      zh: ["森林、海边等自然散步"],
      ja: ["森・海など自然での散歩"],
      ar: ["نزهات في الطبيعة"],
    },
    matchBest: ["HLHH", "LLHL", "HHHL"],
    matchChallenge: ["HHLL", "LLLH"],
  },

  // ============ 7. HLLH - 독립 사냥꾼 ============
  {
    slug: "e-h-s-l-a-l-c-h",
    code: "HLLH",
    emoji: "🎯",
    nickname: {
      ko: "독립 사냥꾼 콤비",
      en: "Independent Hunter Duo",
      de: "Das unabhängige Jäger-Duo",
      es: "El Dúo Cazador Independiente",
      zh: "独立猎人组合",
      ja: "独立ハンター コンビ",
      ar: "ثنائي الصياد المستقل",
    },
    tagline: {
      ko: "활동적이고 독립적, 자기 페이스가 확실한 프로페셔널 콤비",
      en: "Active, independent, and firmly self-paced professionals.",
      de: "Aktiv, unabhängig und selbstbestimmt.",
      es: "Activo, independiente y con ritmo propio firme.",
      zh: "活跃、独立、有明确自我节奏的专业组合",
      ja: "活動的で独立的、自分のペースが確実なプロフェッショナルコンビ",
      ar: "نشيط ومستقل ويسير بإيقاعه الخاص.",
    },
    description: {
      ko: "이 콤비는 서로에게 강한 신뢰가 있지만 각자의 공간과 시간을 존중합니다. 반려동물은 야외 활동을 즐기지만 낯선 이의 접근은 단호히 거절하고, 보호자 역시 조용하고 자립적인 성향입니다. 훈련은 자율성을 존중하는 방식일 때 최고의 효과를 냅니다.",
      en: "This duo shares strong trust but respects each other's space and time. Your pet enjoys outdoor activity but firmly rejects strangers' approach, and you're quiet and self-reliant. Training works best with autonomy-respecting methods.",
      de: "Dieses Duo teilt starkes Vertrauen, respektiert aber gegenseitigen Raum.",
      es: "Este dúo comparte una fuerte confianza pero respeta el espacio mutuo.",
      zh: "这个组合彼此信任深厚，但尊重各自的空间和时间。",
      ja: "このコンビは互いに強い信頼があるが各自の空間と時間を尊重します。",
      ar: "يتشارك هذا الثنائي ثقة قوية لكنه يحترم مساحة كل منهما.",
    },
    strengths: {
      ko: ["독립성 강해 혼자 잘 지냄", "자기 페이스로 훈련 흡수", "야외 활동 능력 뛰어남", "신뢰 관계 매우 견고"],
      en: ["Strong independence — comfortable alone", "Absorbs training at own pace", "Excellent outdoor capability", "Very solid trust bond"],
      de: ["Starke Unabhängigkeit"],
      es: ["Fuerte independencia"],
      zh: ["独立性强"],
      ja: ["独立性が強く一人でよく過ごす"],
      ar: ["استقلالية قوية"],
    },
    cautions: {
      ko: ["낯선 사람·동물에 경계 심함", "과도한 스킨십 스트레스", "사회화 훈련 어려움", "다견 가정 부적합"],
      en: ["Strong wariness toward strangers and other animals", "Over-affection causes stress", "Difficult socialization", "Not ideal for multi-pet homes"],
      de: ["Starke Vorsicht gegenüber Fremden"],
      es: ["Fuerte cautela hacia extraños"],
      zh: ["对陌生人和动物警戒心强"],
      ja: ["見知らぬ人や動物に警戒心が強い"],
      ar: ["حذر شديد تجاه الغرباء"],
    },
    activities: {
      ko: ["장거리 자율 산책", "노즈워크·트래킹 놀이", "1:1 훈련만 진행", "조용한 공간에서 관찰 놀이", "정해진 반려동물 친구와만 만남"],
      en: ["Long autonomous walks", "Nose work and tracking games", "1:1 training only", "Observation play in quiet spaces", "Meet only fixed pet friends"],
      de: ["Lange autonome Spaziergänge"],
      es: ["Paseos autónomos largos"],
      zh: ["长距离自主散步"],
      ja: ["長距離の自律散歩"],
      ar: ["نزهات مستقلة طويلة"],
    },
    matchBest: ["HHLH", "LLLH", "HLLL"],
    matchChallenge: ["HHHL", "LHHL"],
  },

  // ============ 8. HLLL - 자유로운 영혼 ============
  {
    slug: "e-h-s-l-a-l-c-l",
    code: "HLLL",
    emoji: "🌪️",
    nickname: {
      ko: "자유로운 영혼 콤비",
      en: "Free Spirit Duo",
      de: "Das freigeistige Duo",
      es: "El Dúo Espíritu Libre",
      zh: "自由灵魂组合",
      ja: "自由な魂コンビ",
      ar: "ثنائي الروح الحرة",
    },
    tagline: {
      ko: "활동적이지만 나머지는 낮아 예측 불가한 자유형 콤비",
      en: "Highly active but unpredictable — the true free spirit.",
      de: "Sehr aktiv, aber unvorhersehbar — der wahre Freigeist.",
      es: "Muy activo pero impredecible — el verdadero espíritu libre.",
      zh: "活跃但其他方面较低，难以预测的自由型组合",
      ja: "活動的だが他は低く予測不可能な自由型コンビ",
      ar: "نشط للغاية لكنه غير متوقع - روح حرة حقيقية.",
    },
    description: {
      ko: "예측하기 어렵고 자기만의 규칙이 있는 콤비입니다. 반려동물은 호기심 폭발형이지만 감정 조절이 서투르고, 보호자도 즉흥적인 편입니다. 훈련은 짧고 재미있게 여러 번 나누어 하는 것이 효과적입니다.",
      en: "Hard to predict, with their own rules. Your pet is curiosity-driven but poor at emotional regulation, and you're impulsive too. Training works best with short, fun, frequent sessions.",
      de: "Schwer vorhersehbar, mit eigenen Regeln.",
      es: "Difícil de predecir, con sus propias reglas.",
      zh: "难以预测，有自己的规则。",
      ja: "予測が難しく自分だけのルールがあるコンビ。",
      ar: "صعب التنبؤ به، وله قواعده الخاصة.",
    },
    strengths: {
      ko: ["호기심 왕성", "새로운 도전 즐김", "야외에서 최고의 컨디션", "자유로운 사고 방식"],
      en: ["Boundless curiosity", "Enjoys new challenges", "Peak performance outdoors", "Free-thinking approach"],
      de: ["Grenzenlose Neugier"],
      es: ["Curiosidad ilimitada"],
      zh: ["好奇心旺盛"],
      ja: ["好奇心旺盛"],
      ar: ["فضول لا حدود له"],
    },
    cautions: {
      ko: ["안전 사고 위험 증가 → 안전장비 필수", "일관된 훈련 어려움", "감정 폭발 후 진정에 시간 필요", "단독 외출 매우 위험"],
      en: ["Higher safety risks — gear is critical", "Difficult consistent training", "Long calm-down time after emotional bursts", "Never let outside alone"],
      de: ["Höhere Sicherheitsrisiken"],
      es: ["Mayores riesgos de seguridad"],
      zh: ["安全事故风险增加"],
      ja: ["安全事故のリスク増加"],
      ar: ["مخاطر أمان أعلى"],
    },
    activities: {
      ko: ["짧고 다양한 놀이 (5-10분)", "매일 새로운 자극 제공", "자기 페이스 존중하는 훈련", "안전한 울타리 공간 확보", "노즈워크 매트 다양하게"],
      en: ["Short, varied play (5-10 min)", "Daily new stimuli", "Pace-respecting training", "Secure fenced spaces", "Diverse nose work mats"],
      de: ["Kurzes, abwechslungsreiches Spiel"],
      es: ["Juego corto y variado"],
      zh: ["短暂多样的游戏"],
      ja: ["短く多様な遊び"],
      ar: ["لعب قصير ومتنوع"],
    },
    matchBest: ["HLLH", "HHLL", "LLLL"],
    matchChallenge: ["LHHH", "LLHH"],
  },

  // ============ 9. LHHH - 평화의 수호자 ============
  {
    slug: "e-l-s-h-a-h-c-h",
    code: "LHHH",
    emoji: "☮️",
    nickname: {
      ko: "평화의 수호자 콤비",
      en: "Peace Guardian Duo",
      de: "Das Friedenswächter-Duo",
      es: "El Dúo Guardián de la Paz",
      zh: "和平守护者组合",
      ja: "平和の守護者コンビ",
      ar: "ثنائي حارس السلام",
    },
    tagline: {
      ko: "차분하지만 다정하고 사교적인 이상적 힐링 콤비",
      en: "Calm yet warm and sociable — the ideal healing duo.",
      de: "Ruhig, aber warmherzig und gesellig — das ideale Heilungsduo.",
      es: "Tranquilo pero cálido y sociable — el dúo sanador ideal.",
      zh: "沉着但亲和且社交的理想治愈组合",
      ja: "落ち着いているが優しく社交的な理想の癒しコンビ",
      ar: "هادئ لكنه دافئ واجتماعي - ثنائي الشفاء المثالي.",
    },
    description: {
      ko: "이 콤비는 함께 있으면 편안함이 스며듭니다. 활력은 적당하지만 사교성과 친화성은 매우 높아, 반려동물이 낯선 손님도 부드럽게 맞이합니다. 감정 조절 능력이 뛰어나 스트레스에도 강한 편이며, 노약자나 어린이 가정에서 특히 안정적입니다. 요양 동물치료(Animal-Assisted Therapy)에 가장 적합한 유형으로 알려져 있습니다.",
      en: "Being together brings deep comfort. Moderate energy but exceptional sociability and warmth — your pet greets even strangers gently. Superior emotional regulation, resilient under stress. Especially stable in homes with elderly or young children. Widely recognized as ideal for Animal-Assisted Therapy.",
      de: "Zusammen sein bringt tiefen Trost.",
      es: "Estar juntos brinda profundo consuelo.",
      zh: "在一起就充满舒适感。",
      ja: "一緒にいると安らぎが染み込むコンビ。",
      ar: "التواجد معاً يجلب راحة عميقة.",
    },
    strengths: {
      ko: ["감정 안정 능력 최고", "다양한 사람과 자연스러운 교류", "노약자 가정에 최적", "테라피 동물 자질 뛰어남"],
      en: ["Peak emotional stability", "Natural interaction with diverse people", "Perfect for elderly-care homes", "Excellent therapy animal traits"],
      de: ["Beste emotionale Stabilität"],
      es: ["Máxima estabilidad emocional"],
      zh: ["情绪稳定能力极佳"],
      ja: ["感情安定能力が最高"],
      ar: ["أعلى استقرار عاطفي"],
    },
    cautions: {
      ko: ["운동 부족으로 비만 위험", "너무 순해 다른 반려동물에 밀릴 수 있음", "지루함을 느끼면 무기력해짐", "정기적 두뇌 자극 필요"],
      en: ["Obesity risk from low exercise", "May be pushed around by more assertive pets", "Boredom leads to lethargy", "Requires regular mental stimulation"],
      de: ["Übergewichtsrisiko durch geringe Bewegung"],
      es: ["Riesgo de obesidad por poco ejercicio"],
      zh: ["运动不足导致肥胖风险"],
      ja: ["運動不足で肥満のリスク"],
      ar: ["خطر السمنة من قلة التمارين"],
    },
    activities: {
      ko: ["짧고 정기적인 산책", "사회화 카페 방문", "가벼운 지능 놀이", "가족·친구와 조용한 시간", "테라피 활동 참여"],
      en: ["Short regular walks", "Socialization café visits", "Light puzzle games", "Quiet time with family and friends", "Therapy activity participation"],
      de: ["Kurze regelmäßige Spaziergänge"],
      es: ["Paseos cortos regulares"],
      zh: ["短暂规律的散步"],
      ja: ["短く定期的な散歩"],
      ar: ["نزهات قصيرة منتظمة"],
    },
    matchBest: ["HHHH", "LLHH", "LHHL"],
    matchChallenge: ["HHLL", "HLLL"],
  },

  // ============ 10. LHHL - 감성 소통가 ============
  {
    slug: "e-l-s-h-a-h-c-l",
    code: "LHHL",
    emoji: "💗",
    nickname: {
      ko: "감성 소통가 콤비",
      en: "Emotional Communicator Duo",
      de: "Das emotionale Kommunikator-Duo",
      es: "El Dúo Comunicador Emocional",
      zh: "感性沟通者组合",
      ja: "感性コミュニケーター コンビ",
      ar: "ثنائي المتواصل العاطفي",
    },
    tagline: {
      ko: "다정하고 사교적이지만 감정 기복이 있는 소통형 콤비",
      en: "Warm and sociable, but with emotional ups and downs.",
      de: "Warmherzig und gesellig, aber mit emotionalen Höhen und Tiefen.",
      es: "Cálido y sociable, pero con altibajos emocionales.",
      zh: "亲和社交但情绪起伏的沟通型组合",
      ja: "優しく社交的だが感情の起伏がある コミュニケーション型コンビ",
      ar: "دافئ واجتماعي لكن مع تقلبات عاطفية.",
    },
    description: {
      ko: "이 콤비는 감정이 풍부하고 표현이 세심합니다. 반려동물은 보호자의 미묘한 감정 변화를 즉각 감지하고 반응합니다. 사교적이지만 감정 조절이 어려워 스트레스 상황에서 예민해질 수 있습니다.",
      en: "Emotionally rich and attentive. Your pet detects and mirrors your subtle emotional shifts instantly. Sociable but emotionally reactive under stress.",
      de: "Emotional reich und aufmerksam.",
      es: "Emocionalmente rico y atento.",
      zh: "情感丰富且细腻。",
      ja: "このコンビは感情豊かで表現が繊細です。",
      ar: "غني عاطفياً ومنتبه.",
    },
    strengths: {
      ko: ["감정 소통 최고", "보호자와의 애착 매우 강함", "친구 관계 잘 유지", "부드러운 훈련 반응 좋음"],
      en: ["Best emotional communication", "Very strong attachment to owner", "Maintains friendships well", "Responds to gentle training"],
      de: ["Beste emotionale Kommunikation"],
      es: ["Mejor comunicación emocional"],
      zh: ["情感沟通极佳"],
      ja: ["感情コミュニケーション最高"],
      ar: ["أفضل تواصل عاطفي"],
    },
    cautions: {
      ko: ["분리불안 위험 높음", "감정 기복이 심할 때 지원 필요", "환경 변화에 민감", "일관된 루틴 필수"],
      en: ["High separation anxiety risk", "Needs support during emotional swings", "Sensitive to environment changes", "Consistent routine essential"],
      de: ["Hohes Trennungsangstrisiko"],
      es: ["Alto riesgo de ansiedad por separación"],
      zh: ["分离焦虑风险高"],
      ja: ["分離不安のリスク高い"],
      ar: ["خطر قلق الانفصال العالي"],
    },
    activities: {
      ko: ["1:1 스킨십 시간", "안정된 루틴 유지", "가벼운 감정 안정 마사지", "차분한 음악 함께 듣기", "친숙한 반려동물 친구와 놀이"],
      en: ["1:1 skin contact time", "Maintain stable routine", "Gentle emotional-calm massage", "Listen to calming music together", "Play with familiar pet friends"],
      de: ["1:1 Hautkontaktzeit"],
      es: ["Tiempo de contacto piel a piel 1:1"],
      zh: ["1:1亲密接触时间"],
      ja: ["1:1のスキンシップ時間"],
      ar: ["وقت الاتصال الجسدي الفردي"],
    },
    matchBest: ["HHHH", "LHHH", "HLHL"],
    matchChallenge: ["HHLL", "HLLL"],
  },

  // ============ 11. LHLH - 사교 관찰자 ============
  {
    slug: "e-l-s-h-a-l-c-h",
    code: "LHLH",
    emoji: "🔍",
    nickname: {
      ko: "사교 관찰자 콤비",
      en: "Social Observer Duo",
      de: "Das gesellige Beobachter-Duo",
      es: "El Dúo Observador Social",
      zh: "社交观察者组合",
      ja: "社交観察者コンビ",
      ar: "ثنائي المُلاحظ الاجتماعي",
    },
    tagline: {
      ko: "차분하게 사교하지만 낯선 상대는 선별하는 지적 콤비",
      en: "Calmly social yet selective — the intellectual duo.",
      de: "Ruhig gesellig, aber wählerisch — das intellektuelle Duo.",
      es: "Socialmente tranquilo pero selectivo — el dúo intelectual.",
      zh: "沉着社交但对陌生对象有所选择的知性组合",
      ja: "落ち着いて社交するが見知らぬ相手は選別する知的コンビ",
      ar: "اجتماعي بهدوء لكنه انتقائي - الثنائي المثقف.",
    },
    description: {
      ko: "이 콤비는 지적이고 신중합니다. 사교성은 있지만 낯선 존재는 관찰 후 판단합니다. 반려동물이 상황을 파악한 후 행동하며, 보호자도 신중하게 결정하는 편입니다.",
      en: "Intellectual and cautious. Sociable but observes strangers before judging. Your pet acts after assessing the situation, and you also make careful decisions.",
      de: "Intellektuell und vorsichtig.",
      es: "Intelectual y cauteloso.",
      zh: "知性且谨慎。",
      ja: "このコンビは知的で慎重です。",
      ar: "مثقف وحذر.",
    },
    strengths: {
      ko: ["상황 판단력 뛰어남", "훈련 이해도 매우 높음", "안정적 친구 관계", "위험 감지 능력"],
      en: ["Excellent situational judgment", "Very high training comprehension", "Stable friendships", "Danger detection ability"],
      de: ["Ausgezeichnetes Situationsurteil"],
      es: ["Excelente juicio situacional"],
      zh: ["情境判断力优秀"],
      ja: ["状況判断力が優れている"],
      ar: ["حكم استثنائي على المواقف"],
    },
    cautions: {
      ko: ["첫 만남에 시간 필요", "낯선 환경 적응 느림", "지나친 자극 스트레스", "새 반려동물 도입 매우 신중히"],
      en: ["First meetings need time", "Slow adaptation to new environments", "Excessive stimuli cause stress", "Very careful with new pet introductions"],
      de: ["Erste Begegnungen brauchen Zeit"],
      es: ["Los primeros encuentros necesitan tiempo"],
      zh: ["初次见面需要时间"],
      ja: ["初対面に時間が必要"],
      ar: ["اللقاءات الأولى تحتاج وقتاً"],
    },
    activities: {
      ko: ["정해진 사교 모임 정기 참여", "지능 놀이 (퍼즐 피더)", "명확한 규칙 있는 훈련", "익숙한 카페 방문", "차분한 산책"],
      en: ["Regular fixed social gatherings", "Intelligence toys (puzzle feeders)", "Rule-based training", "Familiar café visits", "Calm walks"],
      de: ["Regelmäßige festgelegte soziale Zusammenkünfte"],
      es: ["Reuniones sociales fijas regulares"],
      zh: ["定期参加固定社交聚会"],
      ja: ["決まった社交集まりに定期参加"],
      ar: ["تجمعات اجتماعية ثابتة منتظمة"],
    },
    matchBest: ["HHLH", "LLLH", "LHHH"],
    matchChallenge: ["HLLL", "HHLL"],
  },

  // ============ 12. LHLL - 예민한 관계자 ============
  {
    slug: "e-l-s-h-a-l-c-l",
    code: "LHLL",
    emoji: "🎭",
    nickname: {
      ko: "예민한 관계자 콤비",
      en: "Sensitive Socializer Duo",
      de: "Das sensible Beziehungs-Duo",
      es: "El Dúo Socializador Sensible",
      zh: "敏感关系者组合",
      ja: "敏感な関係者コンビ",
      ar: "ثنائي المُتواصل الحساس",
    },
    tagline: {
      ko: "사교적이지만 예민하고 감정 조절이 어려운 섬세한 콤비",
      en: "Sociable yet sensitive — emotionally delicate.",
      de: "Gesellig, aber sensibel — emotional zart.",
      es: "Sociable pero sensible — emocionalmente delicado.",
      zh: "社交但敏感、情绪难以调节的细腻组合",
      ja: "社交的だが敏感で感情調整が難しい繊細なコンビ",
      ar: "اجتماعي لكنه حساس - رقيق عاطفياً.",
    },
    description: {
      ko: "이 콤비는 사람을 좋아하지만 감정 기복이 심합니다. 반려동물은 애정을 원하면서도 예상 못한 자극에 예민하게 반응합니다. 세심한 케어와 안정된 환경이 필수입니다.",
      en: "Loves people but has strong emotional swings. Your pet craves affection but reacts sensitively to unexpected stimuli. Requires meticulous care and stable environment.",
      de: "Liebt Menschen, hat aber starke emotionale Schwankungen.",
      es: "Ama a las personas pero tiene fuertes cambios emocionales.",
      zh: "喜欢人但情绪起伏大。",
      ja: "このコンビは人を好むが感情の起伏が激しい。",
      ar: "يحب الناس لكنه يعاني من تقلبات عاطفية قوية.",
    },
    strengths: {
      ko: ["애정 표현 풍부", "친밀한 관계에 매우 몰입", "감정 감지 능력 뛰어남", "부드러운 훈련 반응 좋음"],
      en: ["Abundant affection", "Deep immersion in close relationships", "Excellent emotional detection", "Responds to gentle training"],
      de: ["Reichliche Zuneigung"],
      es: ["Afecto abundante"],
      zh: ["情感表达丰富"],
      ja: ["愛情表現豊か"],
      ar: ["عاطفة وفيرة"],
    },
    cautions: {
      ko: ["분리불안 매우 위험", "예상 못한 변화에 스트레스 폭발", "훈련 시 부정적 자극 절대 금지", "환경 소음 관리"],
      en: ["Extreme separation anxiety risk", "Explosive stress from unexpected changes", "Never use negative reinforcement", "Manage environmental noise"],
      de: ["Extreme Trennungsangstgefahr"],
      es: ["Riesgo extremo de ansiedad por separación"],
      zh: ["分离焦虑极高风险"],
      ja: ["分離不安が極めて危険"],
      ar: ["خطر قلق الانفصال الشديد"],
    },
    activities: {
      ko: ["안정된 루틴 유지", "긍정 강화 훈련만", "부드러운 마사지·스킨십", "친숙한 몇 명과만 만남", "감정 안정 음악"],
      en: ["Maintain stable routine", "Positive reinforcement only", "Gentle massage and touch", "Meet only a few familiar people", "Emotional-calm music"],
      de: ["Stabile Routine beibehalten"],
      es: ["Mantener rutina estable"],
      zh: ["保持稳定的日常"],
      ja: ["安定したルーティンを維持"],
      ar: ["الحفاظ على روتين مستقر"],
    },
    matchBest: ["LHHL", "LLHL", "HLHL"],
    matchChallenge: ["HHLL", "HLLL"],
  },

  // ============ 13. LLHH - 명상형 힐러 ============
  {
    slug: "e-l-s-l-a-h-c-h",
    code: "LLHH",
    emoji: "🧘",
    nickname: {
      ko: "명상형 힐러 콤비",
      en: "Meditative Healer Duo",
      de: "Das meditative Heiler-Duo",
      es: "El Dúo Sanador Meditativo",
      zh: "冥想型治愈者组合",
      ja: "瞑想型ヒーラー コンビ",
      ar: "ثنائي المُعالج التأملي",
    },
    tagline: {
      ko: "차분하고 다정하지만 낯선 것은 조심하는 힐링 콤비",
      en: "Calm and warm, but cautious with the unfamiliar.",
      de: "Ruhig und warmherzig, aber vorsichtig mit dem Unbekannten.",
      es: "Tranquilo y cálido, pero cauteloso con lo desconocido.",
      zh: "沉着亲和但对陌生事物谨慎的治愈组合",
      ja: "落ち着いて優しいが見知らぬものには慎重な癒しコンビ",
      ar: "هادئ ودافئ لكنه حذر تجاه المجهول.",
    },
    description: {
      ko: "이 콤비는 함께 있으면 시간이 천천히 흐르는 것 같은 평온함이 있습니다. 활력과 사교성은 낮지만 서로에 대한 애정과 감정 안정이 매우 높습니다. 조용한 실내에서 함께 시간 보내기를 좋아하고, 반려동물은 익숙한 소수의 사람에게만 마음을 엽니다.",
      en: "Being together creates a slow-flowing peace. Low energy and sociability, but exceptional mutual affection and emotional stability. Loves quiet indoor time together, and your pet only opens up to a small circle of familiar people.",
      de: "Zusammen sein schafft eine langsam fließende Ruhe.",
      es: "Estar juntos crea una paz de flujo lento.",
      zh: "在一起就有时间缓慢流动的宁静感。",
      ja: "このコンビは一緒にいると時間がゆっくり流れるような平穏があります。",
      ar: "التواجد معاً يخلق سلاماً يتدفق ببطء.",
    },
    strengths: {
      ko: ["감정 안정 능력 최고", "실내 생활에 최적화", "깊은 애착 관계", "스트레스 회복력 강함"],
      en: ["Peak emotional stability", "Optimized for indoor life", "Deep attachment bond", "Strong stress resilience"],
      de: ["Beste emotionale Stabilität"],
      es: ["Máxima estabilidad emocional"],
      zh: ["情绪稳定能力极佳"],
      ja: ["感情安定能力が最高"],
      ar: ["أعلى استقرار عاطفي"],
    },
    cautions: {
      ko: ["운동 부족 → 비만·근육 약화", "낯선 환경 적응 어려움", "지루함을 잘 느낌", "정기적 자극 필요"],
      en: ["Lack of exercise → obesity and muscle weakness", "Difficulty adapting to new environments", "Prone to boredom", "Regular stimulation needed"],
      de: ["Bewegungsmangel"],
      es: ["Falta de ejercicio"],
      zh: ["运动不足"],
      ja: ["運動不足"],
      ar: ["نقص التمارين"],
    },
    activities: {
      ko: ["짧고 규칙적인 산책", "지능 놀이 (퍼즐 피더·노즈워크)", "명상·요가 함께 하기", "차분한 음악 감상", "가족과의 조용한 스킨십"],
      en: ["Short regular walks", "Intelligence play (puzzle feeders, nose work)", "Meditation and yoga together", "Calm music listening", "Quiet skin contact with family"],
      de: ["Kurze regelmäßige Spaziergänge"],
      es: ["Paseos cortos regulares"],
      zh: ["短暂规律的散步"],
      ja: ["短く規則的な散歩"],
      ar: ["نزهات قصيرة منتظمة"],
    },
    matchBest: ["HLHH", "LHHH", "LLHL"],
    matchChallenge: ["HHLL", "HHHL"],
  },

  // ============ 14. LLHL - 조용한 감성가 ============
  {
    slug: "e-l-s-l-a-h-c-l",
    code: "LLHL",
    emoji: "🌙",
    nickname: {
      ko: "조용한 감성가 콤비",
      en: "Quiet Empath Duo",
      de: "Das stille Empath-Duo",
      es: "El Dúo Empático Silencioso",
      zh: "静默感性者组合",
      ja: "静かな感性家コンビ",
      ar: "ثنائي المُتعاطف الهادئ",
    },
    tagline: {
      ko: "조용하고 다정하지만 감정 기복이 있는 섬세한 감성 콤비",
      en: "Quiet and warm, but emotionally sensitive.",
      de: "Ruhig und warmherzig, aber emotional sensibel.",
      es: "Tranquilo y cálido, pero emocionalmente sensible.",
      zh: "安静亲和但情绪起伏的细腻感性组合",
      ja: "静かで優しいが感情の起伏がある繊細な感性コンビ",
      ar: "هادئ ودافئ لكنه حساس عاطفياً.",
    },
    description: {
      ko: "이 콤비는 조용하지만 감정 표현이 세심하고 깊습니다. 반려동물은 보호자의 감정을 매우 정확하게 감지하며, 슬픔이나 스트레스에 있는 사람 곁에 있어주는 능력이 뛰어납니다.",
      en: "Quiet but with subtle, deep emotional expression. Your pet accurately senses your emotions and excels at being present with someone sad or stressed.",
      de: "Ruhig, aber mit subtiler, tiefer emotionaler Ausdrucksweise.",
      es: "Tranquilo pero con expresión emocional sutil y profunda.",
      zh: "安静但情感表达细腻深刻。",
      ja: "このコンビは静かだが感情表現が繊細で深い。",
      ar: "هادئ لكن مع تعبير عاطفي دقيق وعميق.",
    },
    strengths: {
      ko: ["감정 공감 최고", "조용한 애정 표현", "테라피 자질 뛰어남", "실내 반려생활 최적"],
      en: ["Peak emotional empathy", "Quiet affection", "Excellent therapy traits", "Ideal for indoor pet life"],
      de: ["Höchste emotionale Empathie"],
      es: ["Máxima empatía emocional"],
      zh: ["情感共鸣极佳"],
      ja: ["感情共感最高"],
      ar: ["أعلى تعاطف عاطفي"],
    },
    cautions: {
      ko: ["분리불안 위험", "낯선 자극에 위축", "감정 폭발 시 지원 필요", "안정된 환경 필수"],
      en: ["Separation anxiety risk", "Withdrawal from unfamiliar stimuli", "Support needed during emotional bursts", "Stable environment essential"],
      de: ["Trennungsangstrisiko"],
      es: ["Riesgo de ansiedad por separación"],
      zh: ["分离焦虑风险"],
      ja: ["分離不安のリスク"],
      ar: ["خطر قلق الانفصال"],
    },
    activities: {
      ko: ["1:1 스킨십과 대화", "부드러운 마사지", "차분한 실내 놀이", "명상·요가", "익숙한 소수와의 만남"],
      en: ["1:1 skin contact and conversation", "Gentle massage", "Calm indoor play", "Meditation and yoga", "Small familiar gatherings"],
      de: ["1:1 Hautkontakt und Gespräch"],
      es: ["Contacto piel a piel 1:1 y conversación"],
      zh: ["1:1亲密接触和对话"],
      ja: ["1:1のスキンシップと会話"],
      ar: ["الاتصال الجسدي الفردي والمحادثة"],
    },
    matchBest: ["LLHH", "LHHL", "HLHL"],
    matchChallenge: ["HHLL", "HHHL"],
  },

  // ============ 15. LLLH - 고독한 현자 ============
  {
    slug: "e-l-s-l-a-l-c-h",
    code: "LLLH",
    emoji: "🦉",
    nickname: {
      ko: "고독한 현자 콤비",
      en: "Solitary Sage Duo",
      de: "Das einsame Weisen-Duo",
      es: "El Dúo Sabio Solitario",
      zh: "孤独智者组合",
      ja: "孤独な賢者コンビ",
      ar: "ثنائي الحكيم المُنعزل",
    },
    tagline: {
      ko: "차분하고 독립적, 자기 세계가 있는 명상형 콤비",
      en: "Calm, independent, with a deep inner world.",
      de: "Ruhig, unabhängig, mit tiefer innerer Welt.",
      es: "Tranquilo, independiente, con profundo mundo interior.",
      zh: "沉着独立、有自己世界的冥想型组合",
      ja: "落ち着いて独立的、自分の世界がある瞑想型コンビ",
      ar: "هادئ ومستقل، له عالم داخلي عميق.",
    },
    description: {
      ko: "이 콤비는 각자의 시간을 매우 중요시합니다. 반려동물은 혼자 조용히 시간 보내는 것을 즐기고, 보호자도 내향적입니다. 서로 방해하지 않는 배려가 신뢰를 만듭니다.",
      en: "Both value their alone time deeply. Your pet enjoys quiet solo time, and you're introverted too. Mutual non-interference builds trust.",
      de: "Beide schätzen ihre Alleinzeit tief.",
      es: "Ambos valoran profundamente su tiempo a solas.",
      zh: "都非常珍视各自的时间。",
      ja: "このコンビは各自の時間を非常に大切にします。",
      ar: "كلاهما يُقدّر وقته الخاص بعمق.",
    },
    strengths: {
      ko: ["독립성 최고", "혼자 잘 지냄", "차분한 훈련 흡수", "안정된 성격"],
      en: ["Peak independence", "Comfortable alone", "Absorbs calm training", "Stable personality"],
      de: ["Höchste Unabhängigkeit"],
      es: ["Máxima independencia"],
      zh: ["独立性极佳"],
      ja: ["独立性が最高"],
      ar: ["أقصى استقلالية"],
    },
    cautions: {
      ko: ["과도한 스킨십 스트레스", "사회화 훈련 어려움", "낯선 방문객 회피", "다견 가정 부적합"],
      en: ["Over-affection causes stress", "Difficult socialization", "Avoids strangers", "Not ideal for multi-pet homes"],
      de: ["Überzuneigung verursacht Stress"],
      es: ["Sobreafecto causa estrés"],
      zh: ["过度亲密造成压力"],
      ja: ["過度なスキンシップがストレス"],
      ar: ["الود المفرط يُسبب التوتر"],
    },
    activities: {
      ko: ["자율 산책", "혼자만의 공간 확보", "조용한 지능 놀이", "관찰형 놀이 (창밖 보기)", "1:1 시간만"],
      en: ["Autonomous walks", "Provide solo space", "Quiet intelligence play", "Observation play (looking outside)", "1:1 time only"],
      de: ["Autonome Spaziergänge"],
      es: ["Paseos autónomos"],
      zh: ["自主散步"],
      ja: ["自律散歩"],
      ar: ["نزهات مستقلة"],
    },
    matchBest: ["HLLH", "LLLL", "LHLH"],
    matchChallenge: ["HHHL", "HHHH"],
  },

  // ============ 16. LLLL - 신비의 은둔자 ============
  {
    slug: "e-l-s-l-a-l-c-l",
    code: "LLLL",
    emoji: "🌌",
    nickname: {
      ko: "신비의 은둔자 콤비",
      en: "Mysterious Hermit Duo",
      de: "Das geheimnisvolle Einsiedler-Duo",
      es: "El Dúo Ermitaño Misterioso",
      zh: "神秘隐士组合",
      ja: "神秘の隠者コンビ",
      ar: "ثنائي الناسك الغامض",
    },
    tagline: {
      ko: "조용하고 신비로우며 자기만의 세계에 사는 특별 콤비",
      en: "Quiet, mysterious, living in their own universe.",
      de: "Ruhig, geheimnisvoll, lebt in ihrem eigenen Universum.",
      es: "Tranquilo, misterioso, viviendo en su propio universo.",
      zh: "安静神秘、生活在自己世界的特殊组合",
      ja: "静かで神秘的、自分だけの世界に生きる特別コンビ",
      ar: "هادئ وغامض ويعيش في عالمه الخاص.",
    },
    description: {
      ko: "이 콤비는 세상에서 가장 신비로운 조합입니다. 활력·사교·친화·침착 모두 낮아 예측 불가능하고 자기만의 독특한 방식으로 세상을 살아갑니다. 이해하기까지 오래 걸리지만 이해하면 극도로 특별한 관계입니다.",
      en: "The most mysterious combination. Low across all four axes — unpredictable, living life in their own unique way. Takes long to understand but forms an extraordinarily special bond once you do.",
      de: "Die geheimnisvollste Kombination.",
      es: "La combinación más misteriosa.",
      zh: "世界上最神秘的组合。",
      ja: "このコンビは世界で最も神秘的な組み合わせです。",
      ar: "أكثر التركيبات غموضاً.",
    },
    strengths: {
      ko: ["유일무이한 개성", "깊은 내면 세계", "예술적 감성", "특별한 유대감"],
      en: ["Unique individuality", "Deep inner world", "Artistic sensitivity", "Special bond"],
      de: ["Einzigartige Individualität"],
      es: ["Individualidad única"],
      zh: ["独一无二的个性"],
      ja: ["唯一無二の個性"],
      ar: ["فردية فريدة"],
    },
    cautions: {
      ko: ["훈련이 매우 어려움 → 인내 필요", "일반적 방식이 통하지 않음", "환경 변화에 극도로 예민", "전문가 상담 권장"],
      en: ["Extremely difficult training — patience required", "Standard methods don't work", "Extreme sensitivity to environmental changes", "Professional consultation recommended"],
      de: ["Extrem schwieriges Training"],
      es: ["Entrenamiento extremadamente difícil"],
      zh: ["训练极其困难"],
      ja: ["訓練が非常に難しい"],
      ar: ["تدريب صعب للغاية"],
    },
    activities: {
      ko: ["개별 맞춤 활동 개발", "자기 페이스 100% 존중", "관찰형 놀이", "안전한 은신처 제공", "전문 행동학자 상담"],
      en: ["Develop custom activities", "100% pace respect", "Observation play", "Provide safe hideaways", "Consult professional behaviorists"],
      de: ["Individuelle Aktivitäten entwickeln"],
      es: ["Desarrollar actividades personalizadas"],
      zh: ["开发个性化活动"],
      ja: ["個別カスタム活動の開発"],
      ar: ["تطوير أنشطة مخصصة"],
    },
    matchBest: ["LLLH", "HLLL", "LLHH"],
    matchChallenge: ["HHHH", "HHHL"],
  },
];

// 헬퍼: slug로 유형 찾기
export function getTypeBySlug(slug: string): TypeContent | null {
  return TYPES.find((t) => t.slug === slug) || null;
}

// 헬퍼: 표시용 코드로 유형 찾기
export function getTypeByCode(code: string): TypeContent | null {
  return TYPES.find((t) => t.code === code) || null;
}

// 다국어 UI 라벨
export const TYPE_UI_LABELS: Record<Locale, {
  browsAll: string;
  yourType: string;
  tagline: string;
  description: string;
  strengths: string;
  cautions: string;
  activities: string;
  matchBest: string;
  matchChallenge: string;
  takeTest: string;
  backToList: string;
  allTypes: string;
  discoverYours: string;
  discoverDesc: string;
  axisHigh: string;
  axisLow: string;
  axisE: string;
  axisS: string;
  axisA: string;
  axisC: string;
}> = {
  ko: {
    browsAll: "16가지 케미 유형 도감",
    yourType: "당신의 케미 유형",
    tagline: "한 줄 요약",
    description: "이 유형은?",
    strengths: "잘 통하는 점",
    cautions: "살짝 조심할 점",
    activities: "추천 활동",
    matchBest: "환상의 케미",
    matchChallenge: "조심할 케미",
    takeTest: "내 유형 검사하기 →",
    backToList: "← 16가지 유형 도감",
    allTypes: "16가지 유형 전체 보기",
    discoverYours: "우리의 케미 유형이 궁금하다면?",
    discoverDesc: "3분이면 우리만의 케미 코드를 확인할 수 있어요.",
    axisHigh: "높음",
    axisLow: "낮음",
    axisE: "활력",
    axisS: "사교성",
    axisA: "친화성",
    axisC: "침착성",
  },
  en: {
    browsAll: "16 Chemistry Types Catalog",
    yourType: "Your Chemistry Type",
    tagline: "In one line",
    description: "About this type",
    strengths: "What clicks",
    cautions: "What to watch",
    activities: "Recommended activities",
    matchBest: "Fantastic chemistry",
    matchChallenge: "Handle with care",
    takeTest: "Find my type →",
    backToList: "← 16 Types Catalog",
    allTypes: "See all 16 types",
    discoverYours: "Curious about your chemistry?",
    discoverDesc: "Discover your unique chemistry code in 3 minutes.",
    axisHigh: "High",
    axisLow: "Low",
    axisE: "Energy",
    axisS: "Sociability",
    axisA: "Agreeableness",
    axisC: "Calmness",
  },
  de: {
    browsAll: "16 Chemie-Typen Katalog",
    yourType: "Ihr Chemie-Typ",
    tagline: "In einer Zeile",
    description: "Über diesen Typ",
    strengths: "Was passt",
    cautions: "Worauf achten",
    activities: "Empfohlene Aktivitäten",
    matchBest: "Fantastische Chemie",
    matchChallenge: "Mit Vorsicht behandeln",
    takeTest: "Meinen Typ finden →",
    backToList: "← 16 Typen Katalog",
    allTypes: "Alle 16 Typen ansehen",
    discoverYours: "Neugierig auf Ihre Chemie?",
    discoverDesc: "Entdecken Sie Ihren einzigartigen Chemie-Code in 3 Minuten.",
    axisHigh: "Hoch",
    axisLow: "Niedrig",
    axisE: "Energie",
    axisS: "Geselligkeit",
    axisA: "Verträglichkeit",
    axisC: "Ruhe",
  },
  es: {
    browsAll: "Catálogo de 16 Tipos de Química",
    yourType: "Tu Tipo de Química",
    tagline: "En una línea",
    description: "Sobre este tipo",
    strengths: "Lo que encaja",
    cautions: "Qué observar",
    activities: "Actividades recomendadas",
    matchBest: "Química fantástica",
    matchChallenge: "Manejar con cuidado",
    takeTest: "Encuentra mi tipo →",
    backToList: "← Catálogo de 16 Tipos",
    allTypes: "Ver los 16 tipos",
    discoverYours: "¿Curioso sobre tu química?",
    discoverDesc: "Descubre tu código de química único en 3 minutos.",
    axisHigh: "Alto",
    axisLow: "Bajo",
    axisE: "Energía",
    axisS: "Sociabilidad",
    axisA: "Amabilidad",
    axisC: "Calma",
  },
  zh: {
    browsAll: "16种化学类型图鉴",
    yourType: "你的化学类型",
    tagline: "一句话总结",
    description: "关于此类型",
    strengths: "契合之处",
    cautions: "需注意之处",
    activities: "推荐活动",
    matchBest: "绝配化学",
    matchChallenge: "小心处理",
    takeTest: "查找我的类型 →",
    backToList: "← 16种类型图鉴",
    allTypes: "查看全部16种类型",
    discoverYours: "对你们的化学感兴趣？",
    discoverDesc: "3分钟发现你们独特的化学代码。",
    axisHigh: "高",
    axisLow: "低",
    axisE: "活力",
    axisS: "社交",
    axisA: "亲和",
    axisC: "冷静",
  },
  ja: {
    browsAll: "16種類のケミストリータイプ図鑑",
    yourType: "あなたのケミストリータイプ",
    tagline: "一言で",
    description: "このタイプについて",
    strengths: "うまく通じる点",
    cautions: "少し注意する点",
    activities: "おすすめ活動",
    matchBest: "最高のケミストリー",
    matchChallenge: "注意すべきケミストリー",
    takeTest: "私のタイプを検査 →",
    backToList: "← 16種類のタイプ図鑑",
    allTypes: "16種類すべて見る",
    discoverYours: "私たちのケミストリーが気になる？",
    discoverDesc: "3分で私たちだけのケミストリーコードを確認できます。",
    axisHigh: "高い",
    axisLow: "低い",
    axisE: "活力",
    axisS: "社交性",
    axisA: "親和性",
    axisC: "冷静さ",
  },
  ar: {
    browsAll: "كتالوج 16 نوعاً من الكيمياء",
    yourType: "نوع كيميائك",
    tagline: "في سطر واحد",
    description: "حول هذا النوع",
    strengths: "ما يتوافق",
    cautions: "ما يجب مراقبته",
    activities: "الأنشطة الموصى بها",
    matchBest: "كيمياء رائعة",
    matchChallenge: "التعامل بحذر",
    takeTest: "اعثر على نوعي ←",
    backToList: "كتالوج 16 نوعاً →",
    allTypes: "عرض جميع الأنواع الـ 16",
    discoverYours: "فضولي بشأن كيميائك؟",
    discoverDesc: "اكتشف رمز كيميائك الفريد في 3 دقائق.",
    axisHigh: "عالي",
    axisLow: "منخفض",
    axisE: "الطاقة",
    axisS: "الاجتماعية",
    axisA: "اللطف",
    axisC: "الهدوء",
  },
};
